spring:
  application:
    name: cooperativa

  datasource:
    url: jdbc:postgresql://localhost:3333/cooperativa
    username: postgres
    password: 123456
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  cache:
    type: redis
    redis:
      time-to-live: 60000

  jpa:
    show-sql: false
    ddl-auto: update
    properties:
      hibernate:
        id:
          new_generator_mappings: true
          useNewIdGeneratorMappings: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/master.xml

logging:
  level:
    root: INFO
    org.springframework: WARN
    com.cwi.cooperativa: DEBUG
  file:
    name: logs/app.log
    path: /var/logs/cooperativa
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

server:
  error:
    include-stacktrace: never
api:
  cpf:
    base-url: "https://brasilapi.com.br/api/cpf/v1/"